# Generated by Django 3.2.12 on 2022-05-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_rename_scans_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='doctor',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='report',
            name='patient',
            field=models.CharField(max_length=13),
        ),
    ]
