# Generated by Django 3.2.12 on 2022-05-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_auto_20220513_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
