# Generated by Django 3.2.12 on 2022-06-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_report_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='asdasd',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
