# Generated by Django 3.2.12 on 2022-06-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_doctor_asdasd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='asdasd',
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default='', max_length=200, null=True),
        ),
    ]
