# Generated by Django 3.2.12 on 2022-06-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_auto_20220622_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='medical_conditions',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
