# Generated by Django 3.2.12 on 2022-06-23 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_alter_patient_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
    ]
