# Generated by Django 3.2.12 on 2022-06-23 10:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_remove_patient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_conditions',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
