# Generated by Django 3.2.12 on 2022-06-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_alter_patient_medical_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='medical_conditions',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
