# Generated by Django 3.2.12 on 2022-06-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_alter_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_archived',
            field=models.BooleanField(default=True),
        ),
    ]
