# Generated by Django 3.2.12 on 2022-06-27 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_alter_patient_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='institution',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='assigned_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.doctor'),
        ),
    ]
