# Generated by Django 3.2.12 on 2022-06-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_auto_20220627_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='phone_num',
            field=models.CharField(default='', max_length=13),
            preserve_default=False,
        ),
    ]
